### ISSUE TITLE
Replace default icon with Xelite's

### ISSUE THREAD

**Issue by JoeTheHuman** [JoeTheHuman/Scammer-Bingo-Reborn#19]
Will be started when I get back from vacation, this isn't a huge thing, but I'd like to do it to make sure it's done correctly.

**Comment by JoeTheHuman** [comment]
![ic_launcher](https://cloud.githubusercontent.com/assets/11019048/16892097/4daff6fc-4acd-11e6-9b2e-03d37fbfd93e.png)

**Comment by XeliteXirish** [comment]
<3
